name: Publish to NPM

on:
  push:
    tags:
      - v*

jobs:
  publish:
    name: Publish to npmjs.org
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install and build if required
        run: |
          npm ci
          npm run build --if-present
          npm run test --if-present
      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > .npmrc
          npm publish --access public
